sudo: required

language: sh

services:
  - docker

before_install:
  - TAGS=""
  - test "$TRAVIS_BRANCH" = master && TAGS="$TAGS latest" || true
  - test -n "$TRAVIS_TAG"          && TAGS="$TAGS $TRAVIS_TAG" || true
  - test "$TRAVIS_BRANCH" = master && test -n "$TRAVIS_TAG" && TAGS="$TAGS stable" || true

script:
  # - mkdir deploy
  # Windows .exe
  # - docker pull koalaman/winghc
  # - docker run --user="$UID" --rm -v "$PWD:/appdata" koalaman/winghc cuib
  # - for tag in $TAGS; do cp "dist/build/ShellCheck/shellcheck.exe" "deploy/shellcheck-$tag.exe"; done
  # - rm -rf dist || true
  # Linux static executable
  - docker pull haskell
  - docker run -it haskell /bin/sh -c "cd cli && stack build"
  # Misc packaging
  #- ./.prepare_deploy

after_failure:
  - id
  - pwd
  - df -h
  - find . -name '*.log' -type f -exec grep "" /dev/null {} +
  - find . -ls

# deploy:
#   provider: gcs
#   skip_cleanup: true
#   secret_access_key:
#     secure:
#   bucket: shellcheck
#   local-dir: deploy
#   on:
#     repo: koalaman/shellcheck
#     all_branches: true
